SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS `FOOD_TYPE_MAX` INNER JOIN REST_INFO USING (FOOD_TYPE, FAVORITES)
ORDER BY FOOD_TYPE DESC;