-- 코드를 입력하세요
SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_OUTS AS O JOIN ANIMAL_INS AS I USING (ANIMAL_ID, ANIMAL_TYPE, NAME)
WHERE I.SEX_UPON_INTAKE LIKE '%Intact%' AND 
    (O.SEX_UPON_OUTCOME LIKE '%Spayed%' OR O.SEX_UPON_OUTCOME LIKE '%Neutered%')
