-- 코드를 입력하세요
SELECT 
    REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW NATURAL JOIN REST_INFO
WHERE ADDRESS LIKE '%서울시%' OR ADDRESS LIKE '%서울특별시%'
GROUP BY REST_ID, REST_NAME, FOOD_tYPE, FAVORITES, ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC;