-- 코드를 입력하세요

SELECT FLAVOR
FROM FIRST_HALF RIGHT OUTER JOIN
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL_ORDER
     FROM JULY
     GROUP BY FLAVOR) AS TOTAL_JULY USING (FLAVOR)
ORDER BY JULY_TOTAL_ORDER + TOTAL_ORDER DESC
LIMIT 3