-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, PT_NO, APNT.MCDP_CD, DR_NAME, APNT_YMD
FROM 
    (
    SELECT APNT_NO, APNT_YMD, PT_NO, MCDP_CD, MDDR_ID
    FROM APPOINTMENT
    WHERE 
        APNT_YMD >= '2022-04-13' AND APNT_YMD < '2022-04-14' AND
        APNT_CNCL_YN = 'N' AND MCDP_CD = 'CS'
    ) AS APNT
    JOIN DOCTOR ON DOCTOR.DR_ID = APNT.MDDR_ID
    JOIN PATIENT USING (PT_NO)
ORDER BY APNT_YMD ASC;