-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM (
    SELECT WRITER_ID AS USER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE `STATUS` = 'DONE'
    GROUP BY USER_ID
    HAVING TOTAL_SALES >= 700000
    ) AS `FILTERED` NATURAL JOIN USED_GOODS_USER
ORDER BY TOTAL_SALES ASC;