-- 코드를 입력하세요
SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS AS `OUTS` JOIN ANIMAL_INS AS `INS` ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE TIMEDIFF(OUTS.DATETIME, INS.DATETIME) < 0
ORDER BY INS.DATETIME ASC;