-- 코드를 입력하세요
SELECT TITLE, R.BOARD_ID, REPLY_ID, 
    R.WRITER_ID, R.CONTENTS,
    DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
FROM USED_GOODS_REPLY AS R 
    JOIN USED_GOODS_BOARD AS B
    ON R.BOARD_ID = B.BOARD_ID
WHERE
    YEAR(B.CREATED_DATE) = 2022 
    AND MONTH(B.CREATED_DATE) = 10
ORDER BY R.CREATED_DATE ASC, TITLE ASC;
