-- 코드를 작성해주세요
SELECT A.DEPT_ID, B.DEPT_NAME_EN, A.AVG_SAL
FROM (
    SELECT DEPT_ID, ROUND(AVG(SAL)) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
) AS A
JOIN HR_DEPARTMENT AS B ON A.DEPT_ID = B.DEPT_ID
ORDER BY A.AVG_SAL DESC;